### ISSUE TITLE
The world disappeared 

### ISSUE THREAD

**Issue by tacopill** [grifkuba/sota-issues#23] opened 2021-04-27 00:46 UTC
**Describe the bug**
Got grey screen. Entire world missing. 

**To Reproduce**
1. Started the game
2. Deleted the file
3. Close the game
4. Opened new game 
5. Opened new file
6. Got grey screen. 

**Expected behavior**
I expected the world not to have disappeared. 

**Screenshots**

![image](https://user-images.githubusercontent.com/50280385/116168073-a153d900-a6cf-11eb-8c1d-10a9bc7aa9ad.png)
![image](https://user-images.githubusercontent.com/50280385/116168093-b03a8b80-a6cf-11eb-971f-bb3a3f951b66.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
[log_2021-04-26_20-39-51.txt](https://github.com/grifkuba/sota-issues/files/6381127/log_2021-04-26_20-39-51.txt)
[log.txt](https://github.com/grifkuba/sota-issues/files/6381132/log.txt)
[log_2021-04-26_20-34-54.txt](https://github.com/grifkuba/sota-issues/files/6381133/log_2021-04-26_20-34-54.txt)
[log_2021-04-26_20-39-51.txt](https://github.com/grifkuba/sota-issues/files/6381134/log_2021-04-26_20-39-51.txt)

**Please attach `log.txt` to your bug report for faster assistance** (located in C:\Users\{username}\AppData\Roaming\Godot\app_userdata\Seekers-of-the-Aether)

The file was in 

C:\Users\tacopill\AppData\Roaming\Godot\app_userdata\SotA GitHub

**Comment by Moltak1** [comment] 2021-04-27 01:49
The first three errors in the console are because of #24

**Comment by Moltak1** [comment] 2021-04-27 02:30
other three errors are due to #25

**Comment by Moltak1** [comment] 2021-04-27 02:57
The grey screen is caused by a fatal error that was not reported repeating the steps shows this.
fixed by https://github.com/grifkuba/sota-github/pull/57#issue-623923660

**Comment by Sudospective** [comment] 2021-05-04 00:21
Confirmed working after merge. Closing thread.

**Closed as completed by Sudospective** 2021-05-04 00:21 UTC
Labels: bug
